services:
  backend:
    build:
      target: production
    environment:
      NODE_ENV: production
    volumes: []

  frontend:
    build:
      target: production
    environment:
      NODE_ENV: production
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
    volumes: []

  iot-gateway:
    build:
      target: production
    environment:
      NODE_ENV: production
